version: '3.7'
services:
  frontend:
    container_name: frontend-container
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ..:/app
    ports:
      - 5173:5173
    networks:
      - memo-network

networks:
  memo-network:
    external: true